### ISSUE TITLE
xdrip -experimental colorchange of the background window or lettercolor

### ISSUE THREAD

**Issue by wefink** [StephenBlackWasAlreadyTaken/xDrip-Experimental#100]
since update of my os android to version 5 I can not identify where to add the value of my glucose...
the background is greywhite and the letters are white...seems a problem of the updated os version?
maybe it can changed in xdrip progr. to another color???
thanks for help..i can not write one line of progr.sorry
![screenshot_2015-07-19-20-49-00](https://cloud.githubusercontent.com/assets/13422335/8783366/ae3e094c-2f1b-11e5-930c-173e990c105e.jpg)

**Comment by StephenBlackWasAlreadyTaken** [comment]
Yeah it looks like your phone must have a theme that makes its default text color a very faint blue instead of white, it seems its the same color as your icons and text in the notification bar. I should be able to change this for you

**Comment by wefink** [comment]
thank you very much
werner

**Comment by StephenBlackWasAlreadyTaken** [comment]
change was merged into master, I hope it helps!

**Comment by ghost** [comment]
Great job Steven! Speedy response as always...awesome!

Cheers,
Matthias

**Comment by wefink** [comment]
thanks again.   works perfect
werner
[img]http://up.picr.de/22600510vw.jpg[/img]

**Comment by wefink** [comment]
all done
