### ISSUE TITLE
Vibrations turn on/off

### ISSUE THREAD

**Issue by infoneo** [StephenBlackWasAlreadyTaken/xDrip-Experimental#113]
In the EditAlert there should be "use vibration" checkbox. Sometimes vibrations are louder than chosen alarm sound.

**Comment by tzachi-dar** [comment]
You have a point here, the only way to turn off vibrations is using silent mode.
If there are no objections I'll add this option in a day or two.

**Comment by StephenBlackWasAlreadyTaken** [comment]
I see no reason why not, having the option sounds good to me
