### ISSUE TITLE
Fatal Exception after selection xDrip in bluetoothe scan

### ISSUE THREAD

**Issue by JohanDegraeve** [StephenBlackWasAlreadyTaken/xDrip-Experimental#194]
Device = Samsung galaxy tab 4.8.0 (sm-t335)
Android 5.1.1
Tested on commit with sha 882ef1ed67c853645fb159c247eacfcbc9a81832 but I also noticed in previous versions.

When scanning, and then clicking the xDrip following exception is logged :
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime: FATAL EXCEPTION: main
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime: Process: com.eveningoutpost.dexdrip, PID: 28766
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime: java.lang.RuntimeException: Unable to stop service com.eveningoutpost.dexdrip.Services.DexCollectionService@2f3d66e8: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.speech.tts.TextToSpeech.shutdown()' on a null object reference
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime:     at android.app.ActivityThread.handleStopService(ActivityThread.java:3979)
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime:     at android.app.ActivityThread.access$2400(ActivityThread.java:197)
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1784)
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:145)
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6862)
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime:  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.speech.tts.TextToSpeech.shutdown()' on a null object reference
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime:     at com.eveningoutpost.dexdrip.utils.BgToSpeech.tearDown(BgToSpeech.java:56)
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime:     at com.eveningoutpost.dexdrip.utils.BgToSpeech.tearDownTTS(BgToSpeech.java:39)
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime:     at com.eveningoutpost.dexdrip.Services.DexCollectionService.onDestroy(DexCollectionService.java:121)
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime:     at android.app.ActivityThread.handleStopService(ActivityThread.java:3960)
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime:     at android.app.ActivityThread.access$2400(ActivityThread.java:197) 
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1784) 
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:145) 
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6862) 
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
12-02 21:14:31.765 28766-28766/com.eveningoutpost.dexdrip E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
12-02 21:14:31.765 28766-28944/com.eveningoutpost.dexdrip I/System.out: (HTTPLog)-Static: isSBSettingEnabled false

**Comment by AdrianLxM** [comment]
Thanks for reporting. 
To rank it in my priorities: Does it crash the app altogether or do you just see in in the logs?

**Comment by AdrianLxM** [comment]
May have to just check if tts is null before sending the shutdown message here: https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/blob/master/app/src/main/java/com/eveningoutpost/dexdrip/utils/BgToSpeech.java#L56

**Comment by JohanDegraeve** [comment]
it crashes actually, I'll debug to check what you ask

**Comment by JohanDegraeve** [comment]
Added a breakpoint at line 56 and yes tts is null, when selecting the xDrip from the list of bluetooth modules.

**Comment by AdrianLxM** [comment]
Thanks again!

**Comment by JohanDegraeve** [comment]
let me know if I need to do more tests

**Comment by AdrianLxM** [comment]
I hope this will fix it: https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/197
It would be nice if you could test if that's enough.

**Comment by JohanDegraeve** [comment]
will do
