### ISSUE TITLE
No default text shown in  dialog that asks for "enter base api url"

### ISSUE THREAD

**Issue by JohanDegraeve** [StephenBlackWasAlreadyTaken/xDrip-Experimental#195]
In previous versions there was a default text shown : https://yourpassphrase@{YOUR-SITE}.azurewebsites.net/api/v1/

commit 882ef1ed67c853645fb159c247eacfcbc9a81832
It's not shown anymore
See attached screenshot.
![screenshot_2015-12-02-22-18-50](https://cloud.githubusercontent.com/assets/13840461/11544850/6e3351d4-9944-11e5-84cf-a91fae42ffd5.png)

**Comment by tzachi-dar** [comment]
do you know in what commit did it happen?

Thanks
Tzachi

**Comment by AdrianLxM** [comment]
``` xml
            <SwitchPreference
                android:title="@string/pref_title_api_enabled"
                android:key="cloud_storage_api_enable"
                android:disableDependentsState="false"
                android:summary="@string/pref_summary_api_enabled">
            </SwitchPreference>
            <EditTextPreference
                android:dependency="cloud_storage_api_enable"
                android:title="@string/pref_title_api_url"
                android:key="cloud_storage_api_base"
                android:dialogTitle="@string/pref_dialog_api_url"
                android:dialogMessage="@string/pref_message_api_url"
                android:defaultValue="@string/pref_default_api_url"
                android:inputType="textUri">
            </EditTextPreference>
```

``` xml
    <string name="pref_default_api_url">https://yourpassphrase@{YOUR-SITE}.azurewebsites.net/api/v1/</string>
```

It looks like it is still there.
But I guess this happens in `migrateToNewStyleRestUris()` in `IdempotentMigrations`. Do you think we can just shield the last line and just edit the preference, if the String is non-empty?

Another question arises: Is the Home-Activity a good place to trigger the migrations?
Every time someone opens home it intends to migrate the URLs and the alarm levels.

**Comment by JohanDegraeve** [comment]
@tzachi-dar it was in https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/commit/882ef1ed67c853645fb159c247eacfcbc9a81832
but maybe it was already there before.

**Comment by AdrianLxM** [comment]
This should fix it: https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/199
Without a setting, the empty String was written into it, every time "home" was called.
