### ISSUE TITLE
Performance Issues and other basic things when starting Home

### ISSUE THREAD

**Issue by AdrianLxM** [StephenBlackWasAlreadyTaken/xDrip-Experimental#201]
These are the things I found:

**1) `setupCharts()` is called multiple times during startup**
Possible solution is simple:
_Just call `setupCharts()` once for each update_
- displayCurrentInfo() -> set private.
- setupCharts() -> just called at beginning of `updateCurrentBGInfo()` and not from anywhere else;

**2) Home.onCreate() calls `collectionServiceStarter.start()`.**
So every time we open the App (Home), at least the `onStartCommand()` function of the corresponding service is called.
Do we need that? We have failover timers and to intentionally restart the service you can go to the SystemInformation. And xDrip already works without opening Home as uploader or for hours just with a watch as display.
With xBridgeWixel and btWixel this also has the sideffect, that `lastdata` will get set to `null` (thus deactivating duplicate package detection).  And at least we are pushing the failover timer. Also, if "Send to Pebble" is activated, it will start the Pebble sync.

**3) Having "Send to Pebble" activated (without having a pebble for this test) reproducibly will call PebbleSync.onStartCommand() TWICE** when starting the Home activity (by click on the widget or icon/launcher).
- this happens shortly after Home.onResume() ends
- The data on the home screen does not show until these calls finish. (time consuming as it creates BGGraph-Builder instances that query the database for all values for the chart). Here a Stacktrace:

```
            at com.eveningoutpost.dexdrip.UtilityModels.PebbleSync.onStartCommand(PebbleSync.java:64)
            at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2711)
            at android.app.ActivityThread.access$2100(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1297)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
            at dalvik.system.NativeStart.main(Native Method)
```

At the moment I don't know why this happens TWICE. Once it is because of 2) This is one for @jstevensog?

**4) BgGraphBuilder is used in multiple places for things like getting the `unitizedDeltaString`.**
Every time, a new instance is created. A new instance always *_automatically sets up all the data for the chart_.*
Possible solutions:
- Make the needed functionality static
- Or: generate a separate Utility class
- Or: both of the above

**5) `Home.onCreate()` calls IdemPotententMigrations every time Home is started.** This will only take 10 to 20ms so not much of a problem regarding the time, but I still think it would be better placed at the start of the xdrip-Application (xdrip.java - where Crashlytics are started also)

Resolving 1) and deactivating send-to-pebble (3) and parts of 2)) gave me a speedup from 3.0 +-0.3 seconds to 1.4 +-0.3 seconds. That's something I can live with.
**Please comment and discuss the above points and how we should proceed.** I will definitely resolve 1) but what about 2) to 5)?

**Comment by mgranberry** [comment]
I think 2) is there to handle the case of upgrades.  How do you propose that the collection services be started when the application is installed?  This might be a good candidate for something to go in the Application as well.

4) I would vote that BgGraphBuilder's utilities be carved out into a separate class.  I am ambivalent about whether to make it static or not, because a lot of the places where things are static in xDrip seem to be evidence of design problems, but utilities are usually good candidate for statics.

5) It will actually work better if it is moved to xdrip.java.

**Comment by AdrianLxM** [comment]
PR for 1), 2) and 5): https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/202

**Comment by jstevensog** [comment]
As for 3) I have no idea why PebbleSync.start() would be called from home at all.  It runs as a service, started from preferences, if I understand correctly.  It is also called on a BG reading being captured/ notified, but I am not sure where in the code that happens.  I would remove both these calls and I can test.  I am fairly sure they are not required at all.

Cheers

---- AdrianLxM wrote ----

**Comment by tzachi-dar** [comment]
4) unitizedDeltaString make that a static function. Probably be better in some utility function, but I don't know if we have such a file already.

**Comment by tzachi-dar** [comment]
does 3 still happens after your changes? does it happen only when pebble is set to on?

**Comment by AdrianLxM** [comment]
After merging the pr 202 and John changing PebbleSync, everythig is covered - closing :)
