### ISSUE TITLE
Shortcut to Bg speak readings

### ISSUE THREAD

**Issue by ghost** [StephenBlackWasAlreadyTaken/xDrip-Experimental#214]
Many german users love to use "speak readings" very often per day.
Unfortunately the swich on/off under Settings is not so comfortable.

I would like to request a new feature:

Create a shortcut from main navigation to "bg speak readings".

Would be happy if this could be realized

**Comment by AdrianLxM** [comment]
I also switch it on and off multiple times a day (more often than calibrating or looking at the calibration graph e.g.) and dislike how long it takes to find it in the settings.

I could put it in the menu (menu button) for easy toggling it on and off.

**Comment by ghost** [comment]
Would be great!!!

**Comment by tzachi-dar** [comment]
Is there a way to put some of this things in an advanced tab? in that case we can hide things that people don't use...
You can also have a settings for that since I guess that many people don't use that.

**Comment by AdrianLxM** [comment]
@ceben80: I added it to the menu (menu button). Would you like to test it. (Close xDrip once after enabling the feature).
@tzachi-dar: I made it optional to add it there with a preference. Good Idea!

Here is the PR: https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/217
This is the branch: https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/tree/bgreadings-shortcut

**Comment by ghost** [comment]
Thanks for speedy investigation, great.
I have tested it to my complete satisfaction . It works very well
I would be very happy if it could be added to the master.
![screenshot_2015-12-13-07-14-22-1_2](https://cloud.githubusercontent.com/assets/12679825/11765868/7cf4ae6e-a16b-11e5-86fe-4c086ca057d3.jpg)
