### ISSUE TITLE
Wrong alert sounding

### ISSUE THREAD

**Issue by AdrianLxM** [StephenBlackWasAlreadyTaken/xDrip-Experimental#33]
This happens with ~~the version before the Commits from the 27th and 28th of May~~ today's master branch:

I have two high-Alerts during the day (7 to 22 o'clock): One non-annoying (short SMS notification sound) at 120mg% and another at 175mg% with real alarm sound.

When after a snoozing period ran out, the bg is between those two levels, the annoying alarm goes off even though the BG is just above the notification level.

~~Please drop a line or close the if this was already changed in the mean time. I'll test again with the current version, but it might need some time to actually reproduce this situation in real life.~~ **edit: I reproduced it with today's master branch.**

PS: I really like the new alarm system! Thanks a lot.

**Comment by AdrianLxM** [comment]
Ok, bad bg numbers today, I got it reproduced with the current master branch of today:

It was the alarm I named "hoch alarm tag" that alarmed after a snooze period at bg **167 mg/dl**:
![alarm](http://up.picr.de/22127626pj.png)

This is the snooze menu - it was really "hoch alarm tag":
![alarm snooze](http://up.picr.de/22127624vz.png)

In the settings you see, "hoch alarm tag" was set to **175mg/dl**
![alarm settings](http://up.picr.de/22127625bq.png)

**Comment by AdrianLxM** [comment]
Taking notes:
BG 138mg/dl when snooze time was over:
a) The day alarm rang again even though it is no longer before 22 o'clock.
b) The night alarm didn't ring, even though it is after 22 o*clock.
...
c) on 124mg/dl there no longer is a snoozed alert even though it is still above my higher limit (if this was the stop criterion?)
(not sure: d)after the higher high/above alert, I somehow didn't notice the lower one again even if the snooze period must have been over in the mean time.)

**Comment by tzachi-dar** [comment]
Thanks for reporting this.

I'm looking into it right now and hoping to understand what is going on.

Is the last thing you have reported a new one or just one more occurrence
of the same bug?

In any case, there is one thing that will be a great help:
on setting please check "store logs for troubleshooting"
After the problem happens, please send me the file xdriplogcat.txt. It
should probably be on the directory /sdcard/

Thanks
Tzachi

**Comment by AdrianLxM** [comment]
It's the same bug in my opinion. I just snoozed it for shorter periods to test it.
I'll activate the log. But I'm not sure when it will happen again. I'll try to reproduce it with bg-levels that are more likely to happen.

I'm sorry I'm a bit slow in tracing the code. I just looked over the code that saves the alertsettings/AlertType.

Thanks
Adrian

**Comment by tzachi-dar** [comment]
That is ok.

I believe that I have found the bug, and fixed it, but I still didn't have
a chance to fix it. Hope to do that tomorrow. You can stop trying to
reproduce it.

Hopefully my fix works and will be ready tomorrow.

Thanks
Tzachi

**Comment by AdrianLxM** [comment]
Thanks, you are great!
I'll test the new version then.

**Comment by tzachi-dar** [comment]
you can take the fix from alert_fixes6 and test it.

**Comment by AdrianLxM** [comment]
Thanks a lot!
