### ISSUE TITLE
?CD and ?AD

### ISSUE THREAD

**Issue by danpowell88** [StephenBlackWasAlreadyTaken/xDrip-Experimental#342]
I started xdrip with a sensor that has been in a few days and backdated the start date in the xdrip app (on my tablet test instance of xdrip).

I have a wifi wixel setup that sends the dexterity format to xdrip, I can see it is sending value values

> Uart received '6726272 160768 151872 214 -58 221 3028'
> Server received '{"numberOfRecords":200,"version":1}
> '
> Uart received '6726272 148608 148992 215 -71 225 0'
> Server received '{"numberOfRecords":1,"version":1}
> '
> Uart received '6726272 147968 149248 215 -67 229 0'
> Server received '{"numberOfRecords":1,"version":1}
> '
> Uart received '6726272 149184 150528 215 -83 233 0'
> Server received '{"numberOfRecords":1,"version":1}

Xdrip was showing ?CD when it received the first value and then ?AD after that.

I then tested the same setup with the instance of xdrip that I use everyday with an xbridge and changed the connection type to wifi wixel only and it appears xdrip is getting the values correctly.

I'm not sure exactly what these values mean (count_deviation?) but it appears the wixel is sending valid values

**Comment by tzachi-dar** [comment]
Hi,

It seems that you are using dexterity with some other fw (on the wixel)
than you should.
Dexterity should be using wixel fw from:
https://github.com/tzachi-dar/adrien_de_croy-dexterity-wixel/commit/c5aec8f7cd3c53d2d598406e50a3efaab7ddc4f5

It seems to me that the fw that you are using is of the parakeet, is that
possible?
In any case the numbers that you get are very likely:
6726272 160768 151872 214 -58 221 3028
hash of transmiter id, raw avlue, filtered value, transmitter battery
level, signal strength, transmision id + channel, I have no idea.

This is very similar to what dexterity is using but not exactly the same.

Thanks
Tzachi

**Comment by danpowell88** [comment]
I'll give that a go, I was using hte xdrip-wixel firmware with usb mode enabled.

https://github.com/StephenBlackWasAlreadyTaken/wixel-xDrip/blob/master/apps/dexdrip/dexdrip.c

Which says the format is

`printf("%lu %lu %lu %hhu %d %hhu %d \r\n", pPkt->src_addr,dex_num_decoder(pPkt->raw),dex_num_decoder(pPkt->filtered)*2, pPkt->battery, getPacketRSSI(pPkt),pPkt->txId,adcConvertToMillivolts(adcRead(0)));`

**Comment by danpowell88** [comment]
The issue ended up resolving itself after I entered in another calibration, not sure exactly what was happening though
