### ISSUE TITLE
Moving between phones

### ISSUE THREAD

**Issue by danpowell88** [StephenBlackWasAlreadyTaken/xDrip-Experimental#344]
I'd like to move other to another phone for testing.

Is there a way to setup the calibration data on the other phone, so i dont have to start the sensor again and get it all calibrated?

**Comment by tzachi-dar** [comment]
you need to export your data base on one phone and import it on the other.

you should do it using right click on the top of the xdrip (the 3 dots on the right).

**Comment by danpowell88** [comment]
ah I see, found it, was hidden in the option menu button of my phone
