### ISSUE TITLE
time issue for values

### ISSUE THREAD

**Issue by baembel08** [StephenBlackWasAlreadyTaken/xDrip-Experimental#384]
Hi,

I'm testing xdrip-experimental (release from beginning of week, self cmpiled apk with android studio). I'm Using using it with Dexcom G5 Transmitter and since midday today 09 02 2016 wrong data is computed and stored for time last reading. (see picture). System time for  LG K8 Android 6 is ok. Error logg messages are three month behind real date. 
Quick fix would be nice,
Arndt
![screenshot_2016-09-02-14-42-29](https://cloud.githubusercontent.com/assets/13855068/18207461/945be82a-712b-11e6-92ea-9a1f811c0e49.png)

**Comment by tzachi-dar** [comment]
Seems to me that time of your dexcom is wrong, or on your cell phone).

בתאריך 2 בספט׳ 2016 5:38 אחה״צ,‏ "baembel08" notifications@github.com כתב:

**Comment by baembel08** [comment]
Hi tzachi-dar,
the bg values in the graphic curve are correctly shown, only the values on top  bg value and time since last reading are wrong, when I take a look into sqlite database, the unix time seems to be ok, i can send data, if you want. One interesting thin: I made a query on the userserrors table and did convert time with an online tool. the stored data is transferred to a date in 1958. when I truncate the last thre digits, the parts of a second, everything works fine:
![sqqlite_time](https://cloud.githubusercontent.com/assets/13855068/18210513/29c2a3e2-7139-11e6-9295-b6a2ac3b0ae3.JPG)

**Comment by tzachi-dar** [comment]
Hi,

Time that we are using is in ms, so you need to remove the 3 last digits.

I want to understand which version are you using. Is it the one from: https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental.git 
or the one of the g5 branch?

**Comment by baembel08** [comment]
Hi ,
I'm using the master branch from the url listed above.  I made a download on August, 24 th. I did delete the version yesterday and reinstalled the official G5 xdrip beta version by John Costik without any time issues.

**Comment by tzachi-dar** [comment]
I guess that this is the code for the g5 right now.

**Comment by baembel08** [comment]
Hi tzachi,
I think I've find an answer: converting the timestamp into real date, yoe can see 4 rows where dexcom transmitter obvious did send a wrong time and date as in the pic below:
![dexcom_tr_wron_date](https://cloud.githubusercontent.com/assets/13855068/18243097/bb7a02fe-7359-11e6-9663-5ae356f96461.JPG) 
I don't konow if its only my wrong transmitter, but for future use you could ask for a logical date.

many greetings,

baembel
