### ISSUE TITLE
xdrip - current beta version shows ?AD

### ISSUE THREAD

**Issue by samihusseingit** [StephenBlackWasAlreadyTaken/xDrip-Experimental#393]
Hello,

I am unable to provide any logging/etc, as quite frankly I am not sure where to get it.

However this is what has happened so far.

1-  The sensor was inserted 4 days ago, and I tried to recollect the exact date/time and put that into the xdrip-app. Dexcom G4.  No share.
2-  The xdrip is the one I bought from xdrip.co.uk
3- The x-drip app requested I enter 2 calibration values.  I entered 3.8 and 4.2.
4- Then I changed from the settings to mmol and set low/high limits.

The x-drip has been running for over 2 hours now, but nothing is showing in the graph.  All 0.0

Any help is kindly appreciated.  I didn't know where to put such a question.

Regards,
Susan

**Comment by tzachi-dar** [comment]
If I understand corectly than you have mixed mmol with mgdl. Please add
anorher calibration with the correct units and let us know if it worked.

בתאריך 19 בספט׳ 2016 12:05 לפנה״צ,‏ "samihusseingit" <
notifications@github.com> כתב:

**Comment by samihusseingit** [comment]
Adding another calibration worked.  

THanks
