### ISSUE TITLE
A special alarm setting  is missing

### ISSUE THREAD

**Issue by swissalpine** [StephenBlackWasAlreadyTaken/xDrip-Experimental#41]
I miss an alarm setting. In the stable xDrip I get a message in the status line for each measurement, ie every 5 minutes, even if I do not touch the smartphone.
In the xDrip-Experimental I couldn't realise that. Here the message appears much more frequently, unless I confirm every alarm.
Background of my request is that I could read the alarm messages on my clock (Garmin VivoActive) and I don't like to take the smartphone out of my pocket. If I don't confirm the message appears about every minute, which is too often for me.
My xDrip configuration is this:

![screenshot_2015-06-09-20-03-59](https://cloud.githubusercontent.com/assets/12517693/8065757/e2e07700-0ee3-11e5-86fa-7c19e3c9ad46.png)

I hope I will find that on xDrip-Experimental too.
Thank you!

**Comment by StephenBlackWasAlreadyTaken** [comment]
If you do a persistant notification does that work? If so just turn on run
in foreground

**Comment by swissalpine** [comment]
I think, I couldn't explain what I mean (sorry for my english):

With the alert setting of the screenshot above I get with xDrip this result: Without confirming the alert on the phone I get a new silence text alert which shows in the statusbar with every new bloodclucose reading (every 5 minutes).
With xDrip Experimental I couldn't do that. The alert isn't silent and it reappears much more often (app. every minute) if I don't confirm the alert on the phone. This means that I need to confirm or to snooze the alert every time on the phone. I would like to have a silent alert with text message in the statusbar without the need to confirm (the text message can just stay). This alert should be renewed every time the wixel reads the blood glucose.
Thank you.

**Comment by StephenBlackWasAlreadyTaken** [comment]
and do you want it there all the time? Or only when you are out of range?

**Comment by swissalpine** [comment]
Thank you: You are so fast!
When I'm to low or to high.

**Comment by StephenBlackWasAlreadyTaken** [comment]
kk, current master of experimental allows you to set it to vibrate only (do
you not want vibrating either?) and I am thinking I may add an
'auto-snooze' setting so it does not bug you until it gets swiped away,
still thinking about how to implement that though.

**Comment by swissalpine** [comment]
Great, thank you.
Auto snooth is a solution. And I don't need vibrating. The 'old' xDrip was
very suitable for me in this regard.
Am 09.06.2015 21:52 schrieb "Stephen Black" notifications@github.com:

**Comment by tzachi-dar** [comment]
What does auto snoozing means? It seems to me that the main difference is
that we need to have the timer set every 5 minutes.

Is this needed per alert, or globally?
Globally means that all other alerts functionality is lost, but then this
is just another option in profile, which is print alert only.

So doing it globally is relatively simple.

Thanks
Tzachi
בתאריך 9 ביונ 2015 23:04,‏ "swissalpine" notifications@github.com כתב:

**Comment by StephenBlackWasAlreadyTaken** [comment]
Yeah that's kinda what I was thinking now that I'm playing with it, I
should have a pr in a bit if you could check it out when I put it up tzachi

**Comment by tzachi-dar** [comment]
Yes, I'll do that tomorrow.
 בתאריך 10 ביונ 2015 02:08,‏ "Stephen Black" notifications@github.com כתב:

> Yeah that's kinda what I was thinking now that I'm playing with it, I
> should have a pr in a bit if you could check it out when I put it up tzachi
>

**Comment by StephenBlackWasAlreadyTaken** [comment]
https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/43

**Comment by StephenBlackWasAlreadyTaken** [comment]
should be merged now!
