### ISSUE TITLE
Smart Snooze didn't work

### ISSUE THREAD

**Issue by AdrianLxM** [StephenBlackWasAlreadyTaken/xDrip-Experimental#54]
Situation: 170 double down.

2 programmed alarms: 120 and 170
- Trending/smart snooze didn't work: double arrow down and still alarm went off. I didn't check which one it was when dismissing it, but snoozed is the 170mg/dl one.

Built: 7702ec0 (current master + 1 wakelock added)

**Comment by tzachi-dar** [comment]
Can you please also send the log file?

Please also note that if it was a new alert, than it always fires.
We can see what happened exactly from the log.

Situation: 170 double down.

2 programmed alarms: 120 and 170
- Trending/smart snooze didn't work: double arrow down and still alarm
  went off. I didn't check which one it was when dismissing it, but snoozed
  is the 170mg/dl one.

Built: 7702ec0
https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/commit/7702ec0d2c6dea316f8a74f6a80f4cc336b61950
(current master + 1 wakelog)

—
Reply to this email directly or view it on GitHub
https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/issues/54
.

**Comment by AdrianLxM** [comment]
I didn't log the appropriate Tags, unfortunately.
As I was higher than 170 before I'm pretty sure, that it was snoozed before. (But could have been the snooze of the lower (120) that was over?)

I'm trying to reproduce in a clinical environment with a glucose spike and IV correction ;)
I really like your alarm system and it would be nice to have it in stable soon :)

**Comment by AdrianLxM** [comment]
I tried to reproduce and it worked as intended:

High alarm was snoozing...

21:12 - starting to fall (299 mg/dl, -11.9, single down) after IV insulin
21:13 - went to menu "Snooze Alert" to set Snooze to 5 minutes
21:17 - 260mg/dl, -39.2mg/dl, double down
21:18 - went to menu "Snooze Alert" it sais "0 minutes left". Left menu with back button.
21:22 - 220mg/dl, -40.3mg/dl, double down
21:23 - Menu: "Active alert ... exists (not snoozed)"
21:27 - 183mg/dl, -36.6mg/dl, double down
21:28 - Menu: "Active alert ... exists (not snoozed)"
21:32 - 158mg/dl, -25,2mg/dl, double donw - THE LOWER ALARM SOUNDS
(21:47 - 144mg/dl, -1.2mg/dl, flat ;) )

This is how it is supposed to be as it is below my 170mg/dl threshold and above my 120mg/dl threshold!

It might have been because of my two alarm- setting?
It might have been because it was exacly on the threshold of the high alert (the lower alert should have alarmed like in this case but again was overruled by higher one)?
It might have been just me.

After all, in case of doubt: An alarm should have rung and the one with the higher priority is a good failsafe.

I'll close this Issue tomorow (or you can, If you have read this) and just see if it comes up again or not.

Thank you very much!

**Comment by tzachi-dar** [comment]
This indeed seems working as intended.

As for reproing things:
If you have an extra android device than you can have fake data as much as
you want using this method:

1) In the file WixelReader.java rename the function run to run1, than
rename runfake to run.
2) sellect colection method as wifi wixel.
3) set list of recievers to 127.0.0.1:50005

now, things work as usual. That is add double calibration...
On some devices this only works when you are connected to a computer, but
you will have readings going up and down...

Thanks
Tzachi

**Comment by AdrianLxM** [comment]
Ok thanks. I'll close it then. :)
