### ISSUE TITLE
Adapt activities to small screen

### ISSUE THREAD

**Issue by AdrianLxM** [StephenBlackWasAlreadyTaken/xDrip-Experimental#55]
I'll just list what I find that stops xDrip from working on a small watch:

**Missing vertical scrolling:**
activity_start_new_sensor.xml
activity_stop_sensor.xml
activity_double_calibration.xml
....

**Missing horizontal scrolling:**
activity_system_status.xml
...

**Comment by StephenBlackWasAlreadyTaken** [comment]
https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/56

System status already has a vertical scroll and unfortunately mixing the two seems bad, any others we need? How do these ones work on the watch?

**Comment by AdrianLxM** [comment]
I'll test it the next days. ATM I don't have the watch (lend it to a friend for testing).

I think If we make the labels "Collection Method", "Remembered Device" and "Connection Status" shorter (wrap it to two lines), there will be enough space on the right side.
Even the long version number shows (Multiline).
The buttons already work fine :)

Thanks @StephenBlackWasAlreadyTaken !

**Comment by AdrianLxM** [comment]
activity_start_new_sensor.xml
activity_stop_sensor.xml
activity_double_calibration.xml

Those 3 seem to work now. Thanks!
With the double-calibration it's still tricky to find a place to swipe/scroll and not turning the date wheels ;)

**Comment by AdrianLxM** [comment]
How I would solve the problem with SystemStatus:
https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/64
