### ISSUE TITLE
[FeatureRequest] Adding "x Minutes ago" to Home Screen

### ISSUE THREAD

**Issue by AdrianLxM** [StephenBlackWasAlreadyTaken/xDrip-Experimental#57]
... like in NightWatch.
I  think the TextView that shows "signal missed" could be used. (No problem IMHO if "signal missed" and "x Minutes ago" are mutual exclusive).

**Comment by tzachi-dar** [comment]
+1 from me.

**Comment by swissalpine** [comment]
+1

**Comment by AdrianLxM** [comment]
~~This could be a solution: https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/59~~

**Comment by AdrianLxM** [comment]
Here is the current pull request: https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/61

**Comment by AdrianLxM** [comment]
Thanks for merging!
