### ISSUE TITLE
No icon on newer devices

### ISSUE THREAD

**Issue by AdrianLxM** [StephenBlackWasAlreadyTaken/xDrip-Experimental#92]
From the screenshot from newer phones you can see, that there is no icon:
![no icon](https://lh6.googleusercontent.com/-uxJSXrsdl50/VZrG9SOLruI/AAAAAAAAQLg/Cm3cq1Tys3Q/w422-h749-no/Screenshot_2015-07-06-20-20-35.png)

I don't know if it is due to the higher screen resolution / pixel density or the new version per se.

**Comment by viktoschi** [comment]
it is my phone and it set to 1920x1080 @ 560DPI

**Comment by StephenBlackWasAlreadyTaken** [comment]
Closing! thanks @AdrianLxM
